/* Mirrors every Mongoose model exposed by the backend. */

export interface ApiImage {
  public_id?: string;
  url?: string;
  thumbnailUrl?: string;
  width?: number;
  height?: number;
  format?: string;
  bytes?: number;
  alt?: string;
  caption?: string;
  title?: string;
  credit?: string;
  redirectUrl?: string;
  openInNewTab?: boolean;
  nofollow?: boolean;
  lazyLoad?: boolean;
  priority?: boolean;
  responsive?: boolean;
}

export interface Admin {
  _id: string;
  name?: string;
  email: string;
  role: "superadmin" | "editor";
  permissions?: { canPublish?: boolean; canDelete?: boolean };
  createdAt?: string;
}

export interface Category {
  _id: string;
  name: string;
  slug: string;
  description?: string;
  icon?: string;
  seoTitle?: string;
  seoDescription?: string;
  showOnHome?: boolean;
  maxSubTrending?: number;
  order?: number;
  status?: "active" | "inactive";
  autoUpdateEnabled?: boolean;
  dailyAutoUpdateLimit?: number;
  parent?: string | Category | null;
  image?: ApiImage;
  banner?: ApiImage;
  iconImage?: ApiImage;
  color?: string;
  shortLabel?: string;
  priority?: number;
  featured?: boolean;
  hidden?: boolean;
  showInMenu?: boolean;
  showInFooter?: boolean;
  redirectUrl?: string;
  focusKeyword?: string;
  metaTitle?: string;
  metaDescription?: string;
  canonicalUrl?: string;
  robots?: string;
  ogImage?: ApiImage;
  articleCount?: number;
  coverImage?: ApiImage | null;
  children?: Category[];
  createdAt?: string;
  updatedAt?: string;
}

export interface Tag {
  _id: string;
  name: string;
  slug: string;
  description?: string;
  seoTitle?: string;
  seoDescription?: string;
  focusKeyword?: string;
  usageCount?: number;
  featured?: boolean;
  status?: "active" | "inactive";
  createdAt?: string;
}

export interface Author {
  name?: string;
  slug?: string;
  image?: ApiImage;
  bio?: string;
  designation?: string;
  email?: string;
  redirectUrl?: string;
  social?: { twitter?: string; instagram?: string; linkedin?: string; website?: string };
}

export interface ContentBlock {
  type: "text" | "image" | "link" | "affiliate" | "html" | "video" | "quote" | "embed";
  value?: unknown;
  meta?: Record<string, unknown>;
}

export interface AffiliateLink {
  title?: string;
  link?: string;
  buttonText?: string;
  productImage?: string;
  price?: string;
  clicks?: number;
  isAutoInjected?: boolean;
}

export interface ArticleVideo {
  url?: string;
  thumbnail?: ApiImage;
  title?: string;
  caption?: string;
  redirectUrl?: string;
  provider?: string;
  duration?: number;
}

export interface InternalLink {
  news?: string | Article;
  anchorText?: string;
  isAutoLinked?: boolean;
}

export type ArticleStatus = "draft" | "published" | "archived" | "scheduled" | "trash";

export interface Article {
  _id: string;
  title: string;
  slug?: string;
  subtitle?: string;
  description: string;
  shortDescription?: string;
  longDescription?: string;
  excerpt?: string;
  content?: string;
  contentBlocks?: ContentBlock[];

  category?: Category | string | null;
  subCategory?: Category | string | null;
  tags?: Array<Tag | string>;
  tagNames?: string[];

  featuredImage?: ApiImage;
  ogImage?: ApiImage;
  twitterImage?: ApiImage;
  gallery?: ApiImage[];
  videos?: ArticleVideo[];

  author?: Author;

  affiliateLinks?: AffiliateLink[];
  sourceLinks?: string[];
  externalLink?: string;
  adsLink?: string;
  internalLinks?: InternalLink[];
  relatedNews?: Array<Article | string>;

  featured?: boolean;
  trending?: boolean;
  popular?: boolean;
  breakingNews?: boolean;
  editorsPick?: boolean;
  isMainTrending?: boolean;
  isSubTrending?: boolean;
  isCategoryTrending?: boolean;
  isCategorySubTrending?: boolean;
  priority?: number;
  homeOrder?: number;

  status?: ArticleStatus;
  publishedDate?: string;
  scheduledAt?: string | null;
  updatedDate?: string;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string | null;

  readTime?: number;
  views?: number;
  clicks?: number;
  likes?: number;
  shareCount?: number;
  bookmarks?: number;

  language?: string;
  country?: string;
  region?: string;
  destination?: string;

  sourceName?: string;
  sourceUrl?: string;
  canonicalUrl?: string;

  seoTitle?: string;
  seoDescription?: string;
  seoKeywords?: string[];
  metaTitle?: string;
  metaDescription?: string;
  focusKeyword?: string;
  robots?: string;
  seoScore?: number;
  seoAutoGenerated?: boolean;
  seoSuggestions?: Array<{ field?: string; suggestion?: string; applied?: boolean }>;
  seoLastOptimizedAt?: string;
  schemaMarkup?: unknown;

  cta?: { label?: string; url?: string; style?: "primary" | "secondary" | "ghost"; openInNewTab?: boolean };
  advertisement?: { code?: string; position?: string; enabled?: boolean };

  aiGenerated?: boolean;
  autoUpdateEnabled?: boolean;
  lastAutoUpdatedAt?: string;
  createdBy?: "admin" | "ai" | "import";

  importBatchId?: string | null;
  importRowRef?: string;

  warnings?: string[];
}

export interface MediaItem {
  _id: string;
  name: string;
  originalName?: string;
  folder?: string;
  public_id?: string;
  url: string;
  secureUrl?: string;
  thumbnailUrl?: string;
  resourceType?: "image" | "video" | "raw";
  format?: string;
  width?: number;
  height?: number;
  bytes?: number;
  alt?: string;
  caption?: string;
  title?: string;
  credit?: string;
  redirectUrl?: string;
  tags?: string[];
  usageCount?: number;
  createdAt?: string;
}

export type AdPosition =
  | "home-hero" | "home-top" | "home-infeed" | "home-mid"
  | "home-gallery-left" | "home-gallery-right" | "home-gallery"
  | "home-bottom"
  | "sidebar" | "sidebar-sticky"
  | "article-sidebar-top" | "article-sidebar-middle" | "article-sidebar-bottom"
  | "article-top" | "article-inline" | "article-bottom"
  | "category-top" | "category-infeed"
  | "footer" | "mobile-sticky-bottom";

/** `banner` = image's own shape, full slot width. `frame` = fixed slot size. */
export type AdDisplay = "banner" | "frame";

export interface Advertisement {
  _id: string;
  name: string;
  position: AdPosition;
  type: "image" | "script";
  display?: AdDisplay;
  /** Height ceiling in pixels; empty uses the slot's default. */
  maxHeight?: number | null;
  image?: ApiImage;
  scriptCode?: string;
  targetUrl?: string;
  openInNewTab?: boolean;
  categories?: Array<Category | string>;
  devices?: Array<"desktop" | "tablet" | "mobile">;
  priority?: number;
  startsAt?: string | null;
  endsAt?: string | null;
  impressions?: number;
  clicks?: number;
  status?: "active" | "paused";
  createdAt?: string;
}

export interface ContactMessage {
  _id: string;
  name: string;
  email: string;
  subject?: string;
  message: string;
  reply?: { message?: string; repliedAt?: string; repliedBy?: string };
  status?: "new" | "replied" | "closed";
  createdAt?: string;
}

export interface Subscriber {
  _id: string;
  email: string;
  name?: string;
  source?: string;
  status?: "subscribed" | "unsubscribed";
  unsubscribedAt?: string | null;
  createdAt?: string;
}

export type GallerySide = "left" | "right";
export type GalleryRailWidth = "narrow" | "medium" | "wide";
/** Standard IAB creative slots the rail can be framed for. */
export type GalleryRailSize = "auto" | "300x250" | "300x600" | "160x600";

/** Optional banner/ad column beside the homepage gallery grid. */
export interface GalleryRail {
  enabled?: boolean;
  /** How much of the twelve-column row this rail takes. */
  width?: GalleryRailWidth;
  /** "ad" serves whatever is booked on `adPosition`; "banner" uses the fields below. */
  type?: "ad" | "banner";
  size?: GalleryRailSize;
  adPosition?: AdPosition | string;
  heading?: string;
  image?: string;
  imageAlt?: string;
  link?: string;
  openInNewTab?: boolean;
  /** Stretch the rail card to match the grid height. */
  stretch?: boolean;
}

/** One rail per side; both may run at once. */
export interface GalleryRails {
  left?: GalleryRail;
  right?: GalleryRail;
}

export interface GalleryTile {
  article?: Article | string | null;
  image?: string;
  title?: string;
  category?: string;
  link?: string;
  order?: number;
}

export interface HomepageGallery {
  enabled?: boolean;
  title?: string;
  subtitle?: string;
  actionLabel?: string;
  actionLink?: string;
  /** "auto" fills the four tiles from the live feed; "manual" uses `items`. */
  source?: "auto" | "manual";
  items?: GalleryTile[];
  rails?: GalleryRails;
}

export type HomepageSectionKey =
  | "hero"
  | "heroRail"
  | "editorsPicks"
  | "featured"
  | "popular"
  | "latest"
  | "dontMiss"
  | "moreStories";

/** One curated rail: on/off, auto or manual, and the stories pinned to it. */
export interface HomepageRail {
  enabled?: boolean;
  mode?: "auto" | "manual";
  items?: Array<Article | string>;
  limit?: number;
}

export type HomepageSections = Partial<Record<HomepageSectionKey, HomepageRail>>;

export interface HomepageConfig {
  _id?: string;
  mainTrending?: Article | string | null;
  subTrending?: Array<Article | string>;
  categorySections?: Array<{
    category?: Category | string;
    trending?: Article | string | null;
    subTrending?: Array<Article | string>;
  }>;
  customHomeBlocks?: Array<{ title?: string; link?: string; image?: string; order?: number }>;
  gallery?: HomepageGallery;
  sections?: HomepageSections;
}

export interface DashboardStats {
  categories: number;
  totalNews: number;
  publishedNews: number;
  draftNews: number;
  aiNews: number;
  autoUpdateNews: number;
  avgSeoScore: number;
  newContacts: number;
}

export interface ImportIssue {
  row?: number;
  field?: string;
  message?: string;
  value?: string;
}

export interface ImportJob {
  _id?: string;
  batchId: string;
  fileName?: string;
  fileType?: "xlsx" | "csv";
  mode?: "create" | "upsert";
  status: "validated" | "importing" | "completed" | "failed" | "rolled_back";
  totalRows?: number;
  createdCount?: number;
  updatedCount?: number;
  skippedCount?: number;
  errorCount?: number;
  validRows?: number;
  willCreate?: number;
  willUpdate?: number;
  /** Preview: sub-categories the import would add. */
  pendingSubCategories?: string[];
  /** Finished import: sub-categories it added. */
  createdSubCategories?: string[];
  issues?: ImportIssue[];
  processed?: number;
  canRollback?: boolean;
  createdAt?: string;
}

export interface Pagination {
  page: number;
  limit: number;
  total: number;
  pages: number;
  hasMore?: boolean;
}

export interface Paginated<T> {
  success: boolean;
  data: T[];
  pagination: Pagination;
  stats?: { active?: number };
  positions?: AdPosition[];
}
