import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  ArrowLeft,
  Copy,
  ExternalLink,
  Eye,
  Plus,
  Save,
  Trash2,
  X,
} from "lucide-react";
import { SITE_URL, articlesApi, categoriesApi, tagsApi } from "@/admin/lib/api";
import type {
  AffiliateLink,
  ApiImage,
  Article,
  ArticleStatus,
  ArticleVideo,
  Category,
  ContentBlock,
  InternalLink,
  Tag,
} from "@/admin/types";
import {
  ConfirmDialog,
  ErrorBlock,
  Field,
  LoadingBlock,
  SectionCard,
  Spinner,
  StatusBadge,
  Toggle,
  cn,
  formatDate,
  toLocalInput,
} from "@/admin/components/ui";
import { RichTextEditor } from "@/admin/components/RichTextEditor";
import { ArticleImageLinks } from "@/admin/components/ArticleImageLinks";
import { ImageField, mediaToImage } from "@/admin/components/ImageField";
import { MediaPicker } from "@/admin/components/MediaPicker";
import { useToast } from "@/admin/components/Toast";
import { useAuth } from "@/admin/hooks/useAuth";

const TABS = [
  { key: "content", label: "Content" },
  { key: "media", label: "Media" },
  { key: "taxonomy", label: "Taxonomy" },
  { key: "author", label: "Author" },
  { key: "publishing", label: "Publishing" },
  { key: "seo", label: "SEO" },
  { key: "links", label: "Links & CTA" },
  { key: "stats", label: "Stats" },
] as const;

type TabKey = (typeof TABS)[number]["key"];

const EDITORIAL_FLAGS: Array<{ key: keyof Article; label: string; hint: string }> = [
  { key: "featured", label: "Featured", hint: "Shows in the Featured Articles grid" },
  { key: "trending", label: "Trending", hint: "Appears in trending rails" },
  { key: "popular", label: "Popular", hint: "Marks the story as popular" },
  { key: "breakingNews", label: "Breaking news", hint: "Red breaking badge" },
  { key: "editorsPick", label: "Editor's pick", hint: "Editor's Picks column" },
  { key: "isMainTrending", label: "Homepage hero", hint: "The single lead story" },
  { key: "isSubTrending", label: "Homepage rail", hint: "Beside the hero" },
  { key: "isCategoryTrending", label: "Category hero", hint: "Lead story of its category" },
  { key: "isCategorySubTrending", label: "Category rail", hint: "Secondary category story" },
];

/**
 * Only the places an article page actually has. The homepage slots used to be
 * listed here too, which let an editor pick a position this article could
 * never render.
 */
const AD_POSITIONS = [
  "article-top",
  "article-inline",
  "article-bottom",
  "article-sidebar-top",
  "article-sidebar-middle",
  "article-sidebar-bottom",
];

const AD_POSITION_LABEL: Record<string, string> = {
  "article-top": "Above the headline",
  "article-inline": "Inside the article body",
  "article-bottom": "Below the article, before related stories",
  "article-sidebar-top": "Sidebar — top",
  "article-sidebar-middle": "Sidebar — middle",
  "article-sidebar-bottom": "Sidebar — bottom",
};

const EMPTY: Partial<Article> = {
  title: "",
  slug: "",
  subtitle: "",
  description: "",
  shortDescription: "",
  longDescription: "",
  excerpt: "",
  content: "",
  contentBlocks: [],
  tags: [],
  gallery: [],
  videos: [],
  sourceLinks: [],
  affiliateLinks: [],
  internalLinks: [],
  relatedNews: [],
  seoKeywords: [],
  status: "draft",
  language: "en",
  robots: "index, follow",
  priority: 0,
  homeOrder: 0,
  autoUpdateEnabled: false,
  seoAutoGenerated: true,
};

export default function ArticleEditor() {
  const { id } = useParams<{ id: string }>();
  const isNew = !id;
  const navigate = useNavigate();
  const toast = useToast();
  const { can } = useAuth();
  const queryClient = useQueryClient();

  const [tab, setTab] = useState<TabKey>("content");
  const [form, setForm] = useState<Partial<Article>>(EMPTY);
  const [tagText, setTagText] = useState("");
  const [keywordText, setKeywordText] = useState("");
  const [schemaText, setSchemaText] = useState("");
  const [dirty, setDirty] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [galleryPicker, setGalleryPicker] = useState(false);

  const existing = useQuery({
    queryKey: ["article", id],
    queryFn: () => articlesApi.byId(id as string),
    enabled: !isNew,
  });

  const categories = useQuery({
    queryKey: ["categories", "all"],
    queryFn: () => categoriesApi.list({ withCounts: true }),
  });

  const tags = useQuery({ queryKey: ["tags", "all"], queryFn: () => tagsApi.list({ limit: 200 }) });

  const related = useQuery({
    queryKey: ["articles", "related-picker"],
    queryFn: () => articlesApi.list({ limit: 100, sort: "latest", status: "all" }),
  });

  /* ---------------- hydrate ---------------- */

  useEffect(() => {
    const article = existing.data;
    if (!article) return;

    setForm({
      ...article,
      category: typeof article.category === "string" ? article.category : article.category?._id,
      subCategory:
        typeof article.subCategory === "string" ? article.subCategory : article.subCategory?._id,
    });

    setTagText(
      (article.tags || [])
        .map((tag) => (typeof tag === "string" ? tag : tag.name))
        .filter(Boolean)
        .join(", ") || (article.tagNames || []).join(", ")
    );
    setKeywordText((article.seoKeywords || []).join(", "));
    setSchemaText(article.schemaMarkup ? JSON.stringify(article.schemaMarkup, null, 2) : "");
    setDirty(false);
  }, [existing.data]);

  const patch = (next: Partial<Article>) => {
    setForm((prev) => ({ ...prev, ...next }));
    setDirty(true);
  };

  /* ---------------- save ---------------- */

  const buildPayload = (overrides: Partial<Article> = {}): Partial<Article> => {
    const payload: Partial<Article> & Record<string, unknown> = {
      ...form,
      ...overrides,
      tags: tagText
        .split(",")
        .map((entry) => entry.trim())
        .filter(Boolean),
      seoKeywords: keywordText
        .split(",")
        .map((entry) => entry.trim())
        .filter(Boolean),
    };

    // schemaMarkup travels as text and is parsed by the backend.
    payload.schemaMarkup = schemaText.trim() ? schemaText : null;

    // read-only server fields must never be echoed back
    [
      "_id", "views", "clicks", "likes", "shareCount", "bookmarks",
      "createdAt", "updatedAt", "updatedDate", "seoScore", "seoSuggestions",
      "seoLastOptimizedAt", "lastAutoUpdatedAt", "deletedAt", "importBatchId",
      "warnings", "__v",
    ].forEach((key) => delete payload[key]);

    return payload;
  };

  const save = useMutation({
    mutationFn: async (overrides: Partial<Article> = {}) => {
      const payload = buildPayload(overrides);
      if (isNew) return articlesApi.create(payload);
      return articlesApi.update(id as string, payload);
    },
    onSuccess: (article) => {
      const warnings = (article as Article).warnings;
      if (warnings?.length) warnings.forEach((warning) => toast.info(warning));
      toast.success(isNew ? "Article created" : "Article saved");
      setDirty(false);
      void queryClient.invalidateQueries({ queryKey: ["articles"] });
      void queryClient.invalidateQueries({ queryKey: ["dashboard"] });
      if (isNew && article?._id) navigate(`/admin/articles/${article._id}/edit`, { replace: true });
      else void queryClient.invalidateQueries({ queryKey: ["article", id] });
    },
    onError: (error: Error) => toast.error(error.message),
  });

  const duplicate = useMutation({
    mutationFn: () => articlesApi.duplicate(id as string),
    onSuccess: (res) => {
      toast.success("Duplicated as draft");
      navigate(`/admin/articles/${res.data._id}/edit`);
    },
    onError: (error: Error) => toast.error(error.message),
  });

  const remove = useMutation({
    mutationFn: () => articlesApi.remove(id as string),
    onSuccess: () => {
      toast.success("Article deleted");
      navigate("/admin/articles");
    },
    onError: (error: Error) => toast.error(error.message),
  });

  const categoryList = categories.data ?? [];
  const tagList = tags.data?.data ?? [];

  if (!isNew && existing.isLoading) return <LoadingBlock label="Loading article…" />;
  if (!isNew && existing.isError)
    return <ErrorBlock error={existing.error} onRetry={() => void existing.refetch()} />;

  return (
    <div className="space-y-4">
      {/* ---------------- header ---------------- */}
      <header className="flex flex-wrap items-center gap-3">
        <Link to="/admin/articles" className="adm-btn-ghost adm-btn-sm">
          <ArrowLeft className="h-3.5 w-3.5" />
          Articles
        </Link>

        <div className="min-w-0 flex-1">
          <h1 className="clamp-1 font-display text-lg font-extrabold text-ink-900 dark:text-white">
            {isNew ? "New article" : form.title || "Untitled"}
          </h1>
          <div className="mt-0.5 flex flex-wrap items-center gap-2 text-[11px] text-ink-500">
            <StatusBadge status={form.status} />
            {form.slug && <span>/{form.slug}</span>}
            {dirty && <span className="font-bold text-amber-600">Unsaved changes</span>}
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {!isNew && form.slug && (
            <a
              href={`${SITE_URL}/article/${form.slug}`}
              target="_blank"
              rel="noopener noreferrer"
              className="adm-btn-ghost adm-btn-sm"
            >
              <Eye className="h-3.5 w-3.5" />
              Preview
            </a>
          )}

          {!isNew && (
            <button
              type="button"
              className="adm-btn-ghost adm-btn-sm"
              onClick={() => duplicate.mutate()}
              disabled={duplicate.isPending}
            >
              <Copy className="h-3.5 w-3.5" />
              Duplicate
            </button>
          )}

          {!isNew && can("canDelete") && (
            <button
              type="button"
              className="adm-btn-ghost adm-btn-sm text-rose-600"
              onClick={() => setConfirmDelete(true)}
            >
              <Trash2 className="h-3.5 w-3.5" />
              Delete
            </button>
          )}

          <button
            type="button"
            className="adm-btn-ghost"
            onClick={() => save.mutate({ status: "draft" })}
            disabled={save.isPending}
          >
            Save draft
          </button>

          <button
            type="button"
            className="adm-btn-primary"
            onClick={() => save.mutate({})}
            disabled={save.isPending}
          >
            {save.isPending ? <Spinner /> : <Save className="h-4 w-4" />}
            Save
          </button>

          {can("canPublish") && form.status !== "published" && (
            <button
              type="button"
              className="adm-btn-primary bg-emerald-600 hover:bg-emerald-700"
              onClick={() => save.mutate({ status: "published" })}
              disabled={save.isPending}
            >
              Publish
            </button>
          )}
        </div>
      </header>

      {/* ---------------- tabs ---------------- */}
      <div className="adm-card flex flex-wrap gap-1 p-1.5">
        {TABS.map((entry) => (
          <button
            key={entry.key}
            type="button"
            onClick={() => setTab(entry.key)}
            className={cn(
              "rounded-lg px-3 py-1.5 text-[13px] font-bold transition-colors",
              tab === entry.key
                ? "bg-brand-600 text-white"
                : "text-ink-600 hover:bg-ink-100 dark:text-ink-300 dark:hover:bg-ink-800"
            )}
          >
            {entry.label}
          </button>
        ))}
      </div>

      {/* ---------------- panels ---------------- */}
      {tab === "content" && (
        <ContentTab form={form} patch={patch} />
      )}

      {tab === "media" && (
        <MediaTab
          form={form}
          patch={patch}
          openGalleryPicker={() => setGalleryPicker(true)}
        />
      )}

      {tab === "taxonomy" && (
        <TaxonomyTab
          form={form}
          patch={patch}
          categories={categoryList}
          tagList={tagList}
          tagText={tagText}
          setTagText={(value) => {
            setTagText(value);
            setDirty(true);
          }}
        />
      )}

      {tab === "author" && <AuthorTab form={form} patch={patch} />}

      {tab === "publishing" && <PublishingTab form={form} patch={patch} />}

      {tab === "seo" && (
        <SeoTab
          form={form}
          patch={patch}
          keywordText={keywordText}
          setKeywordText={(value) => {
            setKeywordText(value);
            setDirty(true);
          }}
          schemaText={schemaText}
          setSchemaText={(value) => {
            setSchemaText(value);
            setDirty(true);
          }}
        />
      )}

      {tab === "links" && (
        <LinksTab form={form} patch={patch} articles={related.data?.data ?? []} />
      )}

      {tab === "stats" && <StatsTab article={existing.data} form={form} />}

      <MediaPicker
        open={galleryPicker}
        multiple
        onClose={() => setGalleryPicker(false)}
        onSelect={(items) =>
          patch({ gallery: [...(form.gallery || []), ...items.map(mediaToImage)] })
        }
      />

      <ConfirmDialog
        open={confirmDelete}
        title="Delete article"
        message="This permanently removes the article. Use trash instead if you might restore it."
        confirmLabel="Delete forever"
        busy={remove.isPending}
        onCancel={() => setConfirmDelete(false)}
        onConfirm={() => remove.mutate()}
      />
    </div>
  );
}

/* ================================================================== */
/* Tabs                                                                */
/* ================================================================== */

function ContentTab({
  form,
  patch,
}: {
  form: Partial<Article>;
  patch: (next: Partial<Article>) => void;
}) {
  const [blocksText, setBlocksText] = useState(() =>
    JSON.stringify(form.contentBlocks || [], null, 2)
  );
  const [blocksError, setBlocksError] = useState("");

  useEffect(() => {
    setBlocksText(JSON.stringify(form.contentBlocks || [], null, 2));
  }, [form._id]);

  return (
    <div className="space-y-4">
      <SectionCard title="Headline" description="Title, slug and the summaries used across the site.">
        <div className="grid gap-3">
          <Field label="Title" required>
            <input
              value={form.title || ""}
              onChange={(event) => patch({ title: event.target.value })}
              placeholder="Article headline"
              className="adm-input"
            />
          </Field>

          <div className="grid gap-3 sm:grid-cols-2">
            <Field label="Slug" hint="Leave empty to generate from the title">
              <input
                value={form.slug || ""}
                onChange={(event) => patch({ slug: event.target.value })}
                placeholder="article-url-slug"
                className="adm-input"
              />
            </Field>
            <Field label="Subtitle / kicker">
              <input
                value={form.subtitle || ""}
                onChange={(event) => patch({ subtitle: event.target.value })}
                className="adm-input"
              />
            </Field>
          </div>

          <Field label="Short description" required hint="Shown on cards and used as the meta fallback">
            <textarea
              rows={3}
              value={form.description || ""}
              onChange={(event) => patch({ description: event.target.value })}
              className="adm-textarea"
            />
          </Field>

          <div className="grid gap-3 sm:grid-cols-2">
            <Field label="Excerpt" hint="Overrides the auto-generated summary">
              <textarea
                rows={3}
                value={form.excerpt || ""}
                onChange={(event) => patch({ excerpt: event.target.value })}
                className="adm-textarea"
              />
            </Field>
            <Field label="Short description (alias field)">
              <textarea
                rows={3}
                value={form.shortDescription || ""}
                onChange={(event) => patch({ shortDescription: event.target.value })}
                className="adm-textarea"
              />
            </Field>
          </div>

          <Field label="Long description" hint="Optional plain-text intro stored alongside the body">
            <textarea
              rows={3}
              value={form.longDescription || ""}
              onChange={(event) => patch({ longDescription: event.target.value })}
              className="adm-textarea"
            />
          </Field>
        </div>
      </SectionCard>

      <SectionCard
        title="Body"
        description="Paste straight from Notes, Word or a web page — formatting is kept and pasted images are uploaded to the media library automatically."
      >
        <RichTextEditor
          value={form.content || ""}
          onChange={(html) => patch({ content: html })}
        />

        <div className="mt-3 grid gap-3 sm:grid-cols-3">
          <Field label="Read time (minutes)" hint="0 = calculate automatically">
            <input
              type="number"
              min={0}
              value={form.readTime ?? 0}
              onChange={(event) => patch({ readTime: Number(event.target.value) })}
              className="adm-input"
            />
          </Field>
        </div>
      </SectionCard>

      <ArticleImageLinks
        content={form.content || ""}
        onChange={(html) => patch({ content: html })}
      />

      <SectionCard
        title="Legacy content blocks"
        description="Older articles store their body as blocks. Edit the JSON only if you know the shape."
        actions={
          (form.contentBlocks?.length ?? 0) > 0 ? (
            <button
              type="button"
              className="adm-btn-ghost adm-btn-sm"
              onClick={() => {
                // Imported articles keep their body in blocks; lift it into the
                // rich-text field so it can be edited normally.
                const html = (form.contentBlocks || [])
                  .map((block) => {
                    const value = block.value;
                    if (typeof value === "string") {
                      return /<[a-z][\s\S]*>/i.test(value) ? value : `<p>${value}</p>`;
                    }
                    if (value && typeof value === "object") {
                      const record = value as Record<string, unknown>;
                      const text = record.html ?? record.text ?? record.url ?? "";
                      return typeof text === "string" ? text : "";
                    }
                    return "";
                  })
                  .filter(Boolean)
                  .join("\n");

                if (html) patch({ content: `${form.content || ""}${html}` });
              }}
            >
              Copy blocks into the editor
            </button>
          ) : undefined
        }
      >
        <textarea
          rows={8}
          spellCheck={false}
          value={blocksText}
          onChange={(event) => {
            setBlocksText(event.target.value);
            try {
              const parsed = JSON.parse(event.target.value || "[]") as ContentBlock[];
              setBlocksError("");
              patch({ contentBlocks: Array.isArray(parsed) ? parsed : [] });
            } catch {
              setBlocksError("Invalid JSON — changes are not applied until it parses.");
            }
          }}
          className="adm-textarea font-mono text-xs"
        />
        {blocksError && <p className="mt-1 text-xs font-semibold text-rose-600">{blocksError}</p>}
      </SectionCard>
    </div>
  );
}

function MediaTab({
  form,
  patch,
  openGalleryPicker,
}: {
  form: Partial<Article>;
  patch: (next: Partial<Article>) => void;
  openGalleryPicker: () => void;
}) {
  const gallery = form.gallery || [];
  const videos = form.videos || [];

  const updateGallery = (index: number, image: ApiImage | undefined) => {
    const next = [...gallery];
    if (image) next[index] = image;
    else next.splice(index, 1);
    patch({ gallery: next });
  };

  const updateVideo = (index: number, video: Partial<ArticleVideo>) => {
    const next = [...videos];
    next[index] = { ...next[index], ...video };
    patch({ videos: next });
  };

  return (
    <div className="space-y-4">
      <SectionCard title="Featured image" description="Used on cards, the hero and social previews.">
        <ImageField
          label="Featured image"
          value={form.featuredImage}
          onChange={(image) => patch({ featuredImage: image })}
        />
      </SectionCard>

      <SectionCard title="Social images" description="Falls back to the featured image when empty.">
        <div className="grid gap-3 lg:grid-cols-2">
          <ImageField
            label="Open Graph image"
            value={form.ogImage}
            onChange={(image) => patch({ ogImage: image })}
          />
          <ImageField
            label="Twitter image"
            value={form.twitterImage}
            onChange={(image) => patch({ twitterImage: image })}
          />
        </div>
      </SectionCard>

      <SectionCard
        title="Gallery"
        description={`${gallery.length} image(s)`}
        actions={
          <button type="button" className="adm-btn-ghost adm-btn-sm" onClick={openGalleryPicker}>
            <Plus className="h-3.5 w-3.5" />
            Add from library
          </button>
        }
      >
        {gallery.length === 0 ? (
          <p className="py-4 text-sm text-ink-500">No gallery images yet.</p>
        ) : (
          <div className="grid gap-3 lg:grid-cols-2">
            {gallery.map((image, index) => (
              <ImageField
                key={`${image.url}-${index}`}
                label={`Gallery image ${index + 1}`}
                value={image}
                onChange={(next) => updateGallery(index, next)}
              />
            ))}
          </div>
        )}
      </SectionCard>

      <SectionCard
        title="Videos"
        description="YouTube, Vimeo or direct file URLs."
        actions={
          <button
            type="button"
            className="adm-btn-ghost adm-btn-sm"
            onClick={() => patch({ videos: [...videos, { url: "" }] })}
          >
            <Plus className="h-3.5 w-3.5" />
            Add video
          </button>
        }
      >
        {videos.length === 0 ? (
          <p className="py-4 text-sm text-ink-500">No videos attached.</p>
        ) : (
          <div className="space-y-4">
            {videos.map((video, index) => (
              <div key={index} className="rounded-xl border border-ink-200 p-3 dark:border-ink-700">
                <div className="mb-2 flex items-center justify-between">
                  <p className="text-[11px] font-bold uppercase tracking-wide text-ink-500">
                    Video {index + 1}
                  </p>
                  <button
                    type="button"
                    className="adm-btn-ghost adm-btn-sm text-rose-600"
                    onClick={() => patch({ videos: videos.filter((_, i) => i !== index) })}
                  >
                    <X className="h-3.5 w-3.5" />
                  </button>
                </div>

                <div className="grid gap-3 sm:grid-cols-2">
                  <Field label="URL" required>
                    <input
                      value={video.url || ""}
                      onChange={(event) => updateVideo(index, { url: event.target.value })}
                      className="adm-input"
                    />
                  </Field>
                  <Field label="Provider" hint="youtube | vimeo | file | other">
                    <input
                      value={video.provider || ""}
                      onChange={(event) => updateVideo(index, { provider: event.target.value })}
                      className="adm-input"
                    />
                  </Field>
                  <Field label="Title">
                    <input
                      value={video.title || ""}
                      onChange={(event) => updateVideo(index, { title: event.target.value })}
                      className="adm-input"
                    />
                  </Field>
                  <Field label="Caption">
                    <input
                      value={video.caption || ""}
                      onChange={(event) => updateVideo(index, { caption: event.target.value })}
                      className="adm-input"
                    />
                  </Field>
                  <Field label="Redirect URL">
                    <input
                      value={video.redirectUrl || ""}
                      onChange={(event) => updateVideo(index, { redirectUrl: event.target.value })}
                      className="adm-input"
                    />
                  </Field>
                  <Field label="Duration (seconds)">
                    <input
                      type="number"
                      value={video.duration ?? ""}
                      onChange={(event) =>
                        updateVideo(index, {
                          duration: event.target.value ? Number(event.target.value) : undefined,
                        })
                      }
                      className="adm-input"
                    />
                  </Field>
                </div>

                <div className="mt-3">
                  <ImageField
                    label="Video thumbnail"
                    value={video.thumbnail}
                    showAdvanced={false}
                    onChange={(image) => updateVideo(index, { thumbnail: image })}
                  />
                </div>
              </div>
            ))}
          </div>
        )}
      </SectionCard>
    </div>
  );
}

function TaxonomyTab({
  form,
  patch,
  categories,
  tagList,
  tagText,
  setTagText,
}: {
  form: Partial<Article>;
  patch: (next: Partial<Article>) => void;
  categories: Category[];
  tagList: Tag[];
  tagText: string;
  setTagText: (value: string) => void;
}) {
  const addTag = (name: string) => {
    const current = tagText
      .split(",")
      .map((entry) => entry.trim())
      .filter(Boolean);
    if (current.some((entry) => entry.toLowerCase() === name.toLowerCase())) return;
    setTagText([...current, name].join(", "));
  };

  return (
    <div className="space-y-4">
      <SectionCard title="Category" description="Required — drives navigation and related content.">
        <div className="grid gap-3 sm:grid-cols-2">
          <Field label="Primary category" required>
            <select
              value={(form.category as string) || ""}
              onChange={(event) => patch({ category: event.target.value })}
              className="adm-select"
            >
              <option value="">Select a category…</option>
              {categories.map((category) => (
                <option key={category._id} value={category._id}>
                  {category.name}
                </option>
              ))}
            </select>
          </Field>

          <Field label="Sub category">
            <select
              value={(form.subCategory as string) || ""}
              onChange={(event) => patch({ subCategory: event.target.value || null })}
              className="adm-select"
            >
              <option value="">None</option>
              {categories.map((category) => (
                <option key={category._id} value={category._id}>
                  {category.name}
                </option>
              ))}
            </select>
          </Field>
        </div>
      </SectionCard>

      <SectionCard title="Tags" description="Comma separated. Unknown names are created automatically.">
        <Field label="Tags">
          <input
            value={tagText}
            onChange={(event) => setTagText(event.target.value)}
            placeholder="travel, budget, hotels"
            className="adm-input"
          />
        </Field>

        {tagList.length > 0 && (
          <div className="mt-3">
            <p className="adm-label">Quick add</p>
            <div className="flex flex-wrap gap-1.5">
              {tagList.slice(0, 30).map((tag) => (
                <button
                  key={tag._id}
                  type="button"
                  onClick={() => addTag(tag.name)}
                  className="adm-chip bg-ink-100 text-ink-600 transition-colors hover:bg-brand-50 hover:text-brand-700 dark:bg-ink-800 dark:text-ink-300"
                >
                  {tag.name}
                  {typeof tag.usageCount === "number" && ` · ${tag.usageCount}`}
                </button>
              ))}
            </div>
          </div>
        )}
      </SectionCard>

      <SectionCard title="Localisation" description="Used by region and destination browsing.">
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <Field label="Language">
            <input
              value={form.language || ""}
              onChange={(event) => patch({ language: event.target.value })}
              placeholder="en"
              className="adm-input"
            />
          </Field>
          <Field label="Country">
            <input
              value={form.country || ""}
              onChange={(event) => patch({ country: event.target.value })}
              className="adm-input"
            />
          </Field>
          <Field label="Region">
            <input
              value={form.region || ""}
              onChange={(event) => patch({ region: event.target.value })}
              placeholder="Asia"
              className="adm-input"
            />
          </Field>
          <Field label="Destination">
            <input
              value={form.destination || ""}
              onChange={(event) => patch({ destination: event.target.value })}
              placeholder="Goa"
              className="adm-input"
            />
          </Field>
        </div>
      </SectionCard>
    </div>
  );
}

function AuthorTab({
  form,
  patch,
}: {
  form: Partial<Article>;
  patch: (next: Partial<Article>) => void;
}) {
  const author = form.author || {};
  const setAuthor = (next: Partial<typeof author>) => patch({ author: { ...author, ...next } });
  const social = author.social || {};

  return (
    <div className="space-y-4">
      <SectionCard title="Byline" description="Shown on the article page and the author archive.">
        <div className="grid gap-3 sm:grid-cols-2">
          <Field label="Name">
            <input
              value={author.name || ""}
              onChange={(event) => setAuthor({ name: event.target.value })}
              className="adm-input"
            />
          </Field>
          <Field label="Designation">
            <input
              value={author.designation || ""}
              onChange={(event) => setAuthor({ designation: event.target.value })}
              placeholder="Senior editor"
              className="adm-input"
            />
          </Field>
          <Field label="Email">
            <input
              type="email"
              value={author.email || ""}
              onChange={(event) => setAuthor({ email: event.target.value })}
              className="adm-input"
            />
          </Field>
          <Field label="Profile redirect URL">
            <input
              value={author.redirectUrl || ""}
              onChange={(event) => setAuthor({ redirectUrl: event.target.value })}
              className="adm-input"
            />
          </Field>
        </div>

        <div className="mt-3">
          <Field label="Bio">
            <textarea
              rows={3}
              value={author.bio || ""}
              onChange={(event) => setAuthor({ bio: event.target.value })}
              className="adm-textarea"
            />
          </Field>
        </div>

        <div className="mt-3">
          <ImageField
            label="Author photo"
            value={author.image}
            showAdvanced={false}
            onChange={(image) => setAuthor({ image })}
          />
        </div>
      </SectionCard>

      <SectionCard title="Social profiles">
        <div className="grid gap-3 sm:grid-cols-2">
          {(["twitter", "instagram", "linkedin", "website"] as const).map((key) => (
            <Field key={key} label={key[0].toUpperCase() + key.slice(1)}>
              <input
                value={social[key] || ""}
                onChange={(event) => setAuthor({ social: { ...social, [key]: event.target.value } })}
                className="adm-input"
              />
            </Field>
          ))}
        </div>
      </SectionCard>
    </div>
  );
}

function PublishingTab({
  form,
  patch,
}: {
  form: Partial<Article>;
  patch: (next: Partial<Article>) => void;
}) {
  return (
    <div className="space-y-4">
      <SectionCard title="Status & schedule">
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <Field label="Status">
            <select
              value={form.status || "draft"}
              onChange={(event) => patch({ status: event.target.value as ArticleStatus })}
              className="adm-select"
            >
              <option value="draft">Draft</option>
              <option value="published">Published</option>
              <option value="scheduled">Scheduled</option>
              <option value="archived">Archived</option>
              <option value="trash">Trash</option>
            </select>
          </Field>

          <Field label="Published date">
            <input
              type="datetime-local"
              value={toLocalInput(form.publishedDate)}
              onChange={(event) =>
                patch({ publishedDate: event.target.value ? new Date(event.target.value).toISOString() : undefined })
              }
              className="adm-input"
            />
          </Field>

          <Field label="Publish at (schedule)" hint="A future date switches status to scheduled">
            <input
              type="datetime-local"
              value={toLocalInput(form.scheduledAt)}
              onChange={(event) =>
                patch({ scheduledAt: event.target.value ? new Date(event.target.value).toISOString() : null })
              }
              className="adm-input"
            />
          </Field>

          <Field label="Priority" hint="Higher wins in featured rails">
            <input
              type="number"
              value={form.priority ?? 0}
              onChange={(event) => patch({ priority: Number(event.target.value) })}
              className="adm-input"
            />
          </Field>

          <Field label="Home order">
            <input
              type="number"
              value={form.homeOrder ?? 0}
              onChange={(event) => patch({ homeOrder: Number(event.target.value) })}
              className="adm-input"
            />
          </Field>
        </div>
      </SectionCard>

      <SectionCard title="Editorial placement" description="These flags drive the homepage rails.">
        <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
          {EDITORIAL_FLAGS.map((flag) => (
            <Toggle
              key={String(flag.key)}
              label={flag.label}
              hint={flag.hint}
              checked={Boolean(form[flag.key])}
              onChange={(value) => patch({ [flag.key]: value } as Partial<Article>)}
            />
          ))}
        </div>
      </SectionCard>

      <SectionCard title="Automation">
        <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
          <Toggle
            label="AI generated"
            hint="Marks the article as produced by the AI pipeline"
            checked={Boolean(form.aiGenerated)}
            onChange={(value) => patch({ aiGenerated: value })}
          />
          <Toggle
            label="Allow auto-update"
            hint="Lets the daily cron refresh this article"
            checked={Boolean(form.autoUpdateEnabled)}
            onChange={(value) => patch({ autoUpdateEnabled: value })}
          />
          <Toggle
            label="Auto SEO"
            hint="Regenerate SEO fields automatically"
            checked={form.seoAutoGenerated !== false}
            onChange={(value) => patch({ seoAutoGenerated: value })}
          />
        </div>
      </SectionCard>
    </div>
  );
}

function SeoTab({
  form,
  patch,
  keywordText,
  setKeywordText,
  schemaText,
  setSchemaText,
}: {
  form: Partial<Article>;
  patch: (next: Partial<Article>) => void;
  keywordText: string;
  setKeywordText: (value: string) => void;
  schemaText: string;
  setSchemaText: (value: string) => void;
}) {
  const metaTitle = form.metaTitle || form.seoTitle || form.title || "";
  const metaDescription = form.metaDescription || form.seoDescription || form.description || "";

  return (
    <div className="space-y-4">
      <SectionCard title="Search appearance">
        <div className="grid gap-3">
          <div className="grid gap-3 sm:grid-cols-2">
            <Field label="Meta title" hint={`${metaTitle.length} characters (aim for 50–60)`}>
              <input
                value={form.metaTitle || ""}
                onChange={(event) => patch({ metaTitle: event.target.value })}
                className="adm-input"
              />
            </Field>
            <Field label="SEO title (legacy field)">
              <input
                value={form.seoTitle || ""}
                onChange={(event) => patch({ seoTitle: event.target.value })}
                className="adm-input"
              />
            </Field>
          </div>

          <Field label="Meta description" hint={`${metaDescription.length} characters (aim for 150–160)`}>
            <textarea
              rows={3}
              value={form.metaDescription || ""}
              onChange={(event) => patch({ metaDescription: event.target.value })}
              className="adm-textarea"
            />
          </Field>

          <Field label="SEO description (legacy field)">
            <textarea
              rows={2}
              value={form.seoDescription || ""}
              onChange={(event) => patch({ seoDescription: event.target.value })}
              className="adm-textarea"
            />
          </Field>

          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            <Field label="Focus keyword">
              <input
                value={form.focusKeyword || ""}
                onChange={(event) => patch({ focusKeyword: event.target.value })}
                className="adm-input"
              />
            </Field>
            <Field label="Canonical URL">
              <input
                value={form.canonicalUrl || ""}
                onChange={(event) => patch({ canonicalUrl: event.target.value })}
                className="adm-input"
              />
            </Field>
            <Field label="Robots">
              <select
                value={form.robots || "index, follow"}
                onChange={(event) => patch({ robots: event.target.value })}
                className="adm-select"
              >
                <option value="index, follow">index, follow</option>
                <option value="noindex, follow">noindex, follow</option>
                <option value="index, nofollow">index, nofollow</option>
                <option value="noindex, nofollow">noindex, nofollow</option>
              </select>
            </Field>
          </div>

          <Field label="SEO keywords" hint="Comma separated">
            <input
              value={keywordText}
              onChange={(event) => setKeywordText(event.target.value)}
              className="adm-input"
            />
          </Field>
        </div>
      </SectionCard>

      <SectionCard
        title="Google preview"
        description="Roughly how the result will look in search."
      >
        <div className="rounded-xl border border-ink-200 p-4 dark:border-ink-700">
          <p className="text-[13px] text-emerald-700 dark:text-emerald-400">
            {SITE_URL}/article/{form.slug || "article-slug"}
          </p>
          <p className="mt-1 text-lg font-semibold text-[#1a0dab] dark:text-brand-300">
            {metaTitle || "Article title"}
          </p>
          <p className="mt-1 text-sm text-ink-600 dark:text-ink-300">
            {metaDescription.slice(0, 165) || "Meta description preview…"}
          </p>
        </div>
      </SectionCard>

      <SectionCard
        title="Structured data"
        description="JSON-LD injected on the article page. Leave empty for the default NewsArticle schema."
      >
        <textarea
          rows={8}
          spellCheck={false}
          value={schemaText}
          onChange={(event) => setSchemaText(event.target.value)}
          placeholder='{"@context":"https://schema.org","@type":"NewsArticle"}'
          className="adm-textarea font-mono text-xs"
        />
      </SectionCard>

      {(form.seoScore || form.seoSuggestions?.length) && (
        <SectionCard title="SEO analysis" description="Filled in by the optimizer service.">
          <p className="text-sm text-ink-600 dark:text-ink-300">
            Score: <strong>{form.seoScore ?? 0}/100</strong>
          </p>
          {form.seoSuggestions?.length ? (
            <ul className="mt-2 space-y-1.5 text-sm">
              {form.seoSuggestions.map((suggestion, index) => (
                <li key={index} className="rounded-lg bg-ink-50 px-3 py-2 dark:bg-ink-800">
                  <span className="font-bold">{suggestion.field}: </span>
                  {suggestion.suggestion}
                </li>
              ))}
            </ul>
          ) : null}
        </SectionCard>
      )}
    </div>
  );
}

function LinksTab({
  form,
  patch,
  articles,
}: {
  form: Partial<Article>;
  patch: (next: Partial<Article>) => void;
  articles: Article[];
}) {
  const sourceLinks = form.sourceLinks || [];
  const affiliates = form.affiliateLinks || [];
  const internal = form.internalLinks || [];
  const relatedIds = (form.relatedNews || []).map((entry) =>
    typeof entry === "string" ? entry : entry._id
  );

  const cta = form.cta || {};
  const advertisement = form.advertisement || {};

  const updateAffiliate = (index: number, next: Partial<AffiliateLink>) => {
    const list = [...affiliates];
    list[index] = { ...list[index], ...next };
    patch({ affiliateLinks: list });
  };

  const updateInternal = (index: number, next: Partial<InternalLink>) => {
    const list = [...internal];
    list[index] = { ...list[index], ...next };
    patch({ internalLinks: list });
  };

  return (
    <div className="space-y-4">
      <SectionCard title="Attribution">
        <div className="grid gap-3 sm:grid-cols-2">
          <Field label="Source name">
            <input
              value={form.sourceName || ""}
              onChange={(event) => patch({ sourceName: event.target.value })}
              className="adm-input"
            />
          </Field>
          <Field label="Source URL">
            <input
              value={form.sourceUrl || ""}
              onChange={(event) => patch({ sourceUrl: event.target.value })}
              className="adm-input"
            />
          </Field>
          <Field label="External link">
            <input
              value={form.externalLink || ""}
              onChange={(event) => patch({ externalLink: event.target.value })}
              className="adm-input"
            />
          </Field>
          <Field label="Ads link">
            <input
              value={form.adsLink || ""}
              onChange={(event) => patch({ adsLink: event.target.value })}
              className="adm-input"
            />
          </Field>
        </div>

        <div className="mt-3">
          <Field label="Additional source links" hint="One per line">
            <textarea
              rows={3}
              value={sourceLinks.join("\n")}
              onChange={(event) =>
                patch({ sourceLinks: event.target.value.split("\n").map((l) => l.trim()).filter(Boolean) })
              }
              className="adm-textarea"
            />
          </Field>
        </div>
      </SectionCard>

      <SectionCard
        title="Affiliate links"
        actions={
          <button
            type="button"
            className="adm-btn-ghost adm-btn-sm"
            onClick={() => patch({ affiliateLinks: [...affiliates, { title: "", link: "" }] })}
          >
            <Plus className="h-3.5 w-3.5" />
            Add
          </button>
        }
      >
        {affiliates.length === 0 ? (
          <p className="py-3 text-sm text-ink-500">No affiliate links.</p>
        ) : (
          <div className="space-y-3">
            {affiliates.map((link, index) => (
              <div key={index} className="rounded-xl border border-ink-200 p-3 dark:border-ink-700">
                <div className="mb-2 flex items-center justify-between">
                  <p className="text-[11px] font-bold uppercase tracking-wide text-ink-500">
                    Link {index + 1}
                    {typeof link.clicks === "number" && ` · ${link.clicks} clicks`}
                  </p>
                  <button
                    type="button"
                    className="adm-btn-ghost adm-btn-sm text-rose-600"
                    onClick={() => patch({ affiliateLinks: affiliates.filter((_, i) => i !== index) })}
                  >
                    <X className="h-3.5 w-3.5" />
                  </button>
                </div>
                <div className="grid gap-3 sm:grid-cols-2">
                  <Field label="Title">
                    <input
                      value={link.title || ""}
                      onChange={(event) => updateAffiliate(index, { title: event.target.value })}
                      className="adm-input"
                    />
                  </Field>
                  <Field label="URL">
                    <input
                      value={link.link || ""}
                      onChange={(event) => updateAffiliate(index, { link: event.target.value })}
                      className="adm-input"
                    />
                  </Field>
                  <Field label="Button text">
                    <input
                      value={link.buttonText || ""}
                      onChange={(event) => updateAffiliate(index, { buttonText: event.target.value })}
                      className="adm-input"
                    />
                  </Field>
                  <Field label="Price">
                    <input
                      value={link.price || ""}
                      onChange={(event) => updateAffiliate(index, { price: event.target.value })}
                      className="adm-input"
                    />
                  </Field>
                  <Field label="Product image URL" className="sm:col-span-2">
                    <input
                      value={link.productImage || ""}
                      onChange={(event) => updateAffiliate(index, { productImage: event.target.value })}
                      className="adm-input"
                    />
                  </Field>
                </div>
              </div>
            ))}
          </div>
        )}
      </SectionCard>

      <SectionCard
        title="Internal links"
        description="Anchor text pointing at other articles."
        actions={
          <button
            type="button"
            className="adm-btn-ghost adm-btn-sm"
            onClick={() => patch({ internalLinks: [...internal, { anchorText: "" }] })}
          >
            <Plus className="h-3.5 w-3.5" />
            Add
          </button>
        }
      >
        {internal.length === 0 ? (
          <p className="py-3 text-sm text-ink-500">No internal links.</p>
        ) : (
          <div className="space-y-3">
            {internal.map((link, index) => (
              <div key={index} className="grid gap-3 rounded-xl border border-ink-200 p-3 sm:grid-cols-[1fr_1fr_auto] dark:border-ink-700">
                <Field label="Anchor text">
                  <input
                    value={link.anchorText || ""}
                    onChange={(event) => updateInternal(index, { anchorText: event.target.value })}
                    className="adm-input"
                  />
                </Field>
                <Field label="Target article">
                  <select
                    value={typeof link.news === "string" ? link.news : link.news?._id || ""}
                    onChange={(event) => updateInternal(index, { news: event.target.value })}
                    className="adm-select"
                  >
                    <option value="">Select…</option>
                    {articles.map((article) => (
                      <option key={article._id} value={article._id}>
                        {article.title}
                      </option>
                    ))}
                  </select>
                </Field>
                <div className="flex items-end">
                  <button
                    type="button"
                    className="adm-btn-ghost adm-btn-sm text-rose-600"
                    onClick={() => patch({ internalLinks: internal.filter((_, i) => i !== index) })}
                  >
                    <X className="h-3.5 w-3.5" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </SectionCard>

      <SectionCard title="Related articles" description="Manually curated related stories.">
        <select
          multiple
          size={8}
          value={relatedIds}
          onChange={(event) =>
            patch({
              relatedNews: Array.from(event.target.selectedOptions).map((option) => option.value),
            })
          }
          className="adm-select h-auto py-2"
        >
          {articles.map((article) => (
            <option key={article._id} value={article._id}>
              {article.title}
            </option>
          ))}
        </select>
        <p className="mt-1 text-[11px] text-ink-400">
          Hold ⌘/Ctrl to select several. {relatedIds.length} selected.
        </p>
      </SectionCard>

      <SectionCard title="Call to action" description="Button rendered at the end of the article.">
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <Field label="Label">
            <input
              value={cta.label || ""}
              onChange={(event) => patch({ cta: { ...cta, label: event.target.value } })}
              className="adm-input"
            />
          </Field>
          <Field label="URL">
            <input
              value={cta.url || ""}
              onChange={(event) => patch({ cta: { ...cta, url: event.target.value } })}
              className="adm-input"
            />
          </Field>
          <Field label="Style">
            <select
              value={cta.style || "primary"}
              onChange={(event) =>
                patch({ cta: { ...cta, style: event.target.value as "primary" | "secondary" | "ghost" } })
              }
              className="adm-select"
            >
              <option value="primary">Primary</option>
              <option value="secondary">Secondary</option>
              <option value="ghost">Ghost</option>
            </select>
          </Field>
          <div className="flex items-end">
            <Toggle
              label="Open in new tab"
              checked={cta.openInNewTab !== false}
              onChange={(value) => patch({ cta: { ...cta, openInNewTab: value } })}
            />
          </div>
        </div>
      </SectionCard>

      <SectionCard
        title="Article ad override"
        description="Adds a creative to this one article, or turns advertising off for it. Booked ads keep running in the other positions unless you switch ads off here."
      >
        <div className="grid gap-3 sm:grid-cols-3">
          <Field label="Position" hint="Where this article's own creative appears.">
            <select
              value={advertisement.position || ""}
              onChange={(event) =>
                patch({ advertisement: { ...advertisement, position: event.target.value } })
              }
              className="adm-select"
            >
              <option value="">Default</option>
              {AD_POSITIONS.map((position) => (
                <option key={position} value={position}>
                  {AD_POSITION_LABEL[position] || position}
                </option>
              ))}
            </select>
          </Field>
          <div className="flex items-end">
            <Toggle
              label="Ads enabled"
              hint="Off hides every ad on this article, booked ones included."
              checked={advertisement.enabled !== false}
              onChange={(value) => patch({ advertisement: { ...advertisement, enabled: value } })}
            />
          </div>
          <Field
            label="Custom ad code"
            className="sm:col-span-3"
            hint="HTML or a script tag. Left empty, the position shows whatever is booked for it under Advertisements."
          >
            <textarea
              rows={4}
              value={advertisement.code || ""}
              onChange={(event) =>
                patch({ advertisement: { ...advertisement, code: event.target.value } })
              }
              className="adm-textarea font-mono text-xs"
            />
          </Field>
        </div>
      </SectionCard>
    </div>
  );
}

function StatsTab({ article, form }: { article?: Article; form: Partial<Article> }) {
  const rows: Array<[string, string | number]> = [
    ["Views", article?.views ?? 0],
    ["Clicks", article?.clicks ?? 0],
    ["Likes", article?.likes ?? 0],
    ["Shares", article?.shareCount ?? 0],
    ["Bookmarks", article?.bookmarks ?? 0],
    ["Read time", `${form.readTime ?? 0} min`],
    ["SEO score", article?.seoScore ?? 0],
    ["Created by", article?.createdBy ?? "—"],
    ["Created", formatDate(article?.createdAt)],
    ["Last updated", formatDate(article?.updatedAt)],
    ["Content updated", formatDate(article?.updatedDate)],
    ["Last auto-update", formatDate(article?.lastAutoUpdatedAt)],
    ["SEO optimised", formatDate(article?.seoLastOptimizedAt)],
    ["Deleted at", formatDate(article?.deletedAt)],
    ["Import batch", article?.importBatchId || "—"],
    ["Import row ref", article?.importRowRef || "—"],
  ];

  return (
    <SectionCard title="Article statistics" description="Read-only counters maintained by the backend.">
      <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
        {rows.map(([label, value]) => (
          <div key={label} className="rounded-lg border border-ink-200 p-3 dark:border-ink-700">
            <p className="text-[11px] font-bold uppercase tracking-wide text-ink-400">{label}</p>
            <p className="mt-1 truncate font-display text-[15px] font-bold text-ink-900 dark:text-white">
              {String(value)}
            </p>
          </div>
        ))}
      </div>

      {article?.slug && (
        <a
          href={`${SITE_URL}/article/${article.slug}`}
          target="_blank"
          rel="noopener noreferrer"
          className="adm-btn-ghost adm-btn-sm mt-4"
        >
          <ExternalLink className="h-3.5 w-3.5" />
          Open on the live site
        </a>
      )}
    </SectionCard>
  );
}
